// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrenIstasyonlar.DataAccess.Context;

#nullable disable

namespace TrenIstasyonlar.DataAccess.Migrations
{
    [DbContext(typeof(TrenIstasyonlariDbContext))]
    partial class TrenIstasyonlariDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrenIstasyonlar.DataAccess.Entities.Istasyon", b =>
                {
                    b.Property<int>("IstasyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IstasyonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IstasyonId"));

                    b.Property<string>("IstasyonAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IstasyonAdres")
                        .HasMaxLength(200)
                        .HasColumnType("nchar(200)")
                        .IsFixedLength();

                    b.Property<string>("IstasyonKonum")
                        .HasMaxLength(200)
                        .HasColumnType("nchar(200)")
                        .IsFixedLength();

                    b.HasKey("IstasyonId");

                    b.ToTable("Istasyon", (string)null);
                });

            modelBuilder.Entity("TrenIstasyonlar.DataAccess.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KullaniciID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanici", (string)null);
                });

            modelBuilder.Entity("TrenIstasyonlar.DataAccess.Entities.Sefer", b =>
                {
                    b.Property<int>("SeferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SeferID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeferId"));

                    b.Property<int?>("KalkisIstasyonId")
                        .HasColumnType("int")
                        .HasColumnName("KalkisIstasyonID");

                    b.Property<DateTime?>("KalkisSaati")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VarisIstasyonId")
                        .HasColumnType("int")
                        .HasColumnName("VarisIstasyonID");

                    b.Property<DateTime?>("VarisSaati")
                        .HasColumnType("datetime2");

                    b.HasKey("SeferId");

                    b.HasIndex("KalkisIstasyonId");

                    b.HasIndex("VarisIstasyonId");

                    b.ToTable("Sefer", (string)null);
                });

            modelBuilder.Entity("TrenIstasyonlar.DataAccess.Entities.Sefer", b =>
                {
                    b.HasOne("TrenIstasyonlar.DataAccess.Entities.Istasyon", "KalkisIstasyon")
                        .WithMany("SeferKalkisIstasyons")
                        .HasForeignKey("KalkisIstasyonId")
                        .HasConstraintName("FK_Sefer_Istasyon");

                    b.HasOne("TrenIstasyonlar.DataAccess.Entities.Istasyon", "VarisIstasyon")
                        .WithMany("SeferVarisIstasyons")
                        .HasForeignKey("VarisIstasyonId")
                        .HasConstraintName("FK_Sefer_Istasyon1");

                    b.Navigation("KalkisIstasyon");

                    b.Navigation("VarisIstasyon");
                });

            modelBuilder.Entity("TrenIstasyonlar.DataAccess.Entities.Istasyon", b =>
                {
                    b.Navigation("SeferKalkisIstasyons");

                    b.Navigation("SeferVarisIstasyons");
                });
#pragma warning restore 612, 618
        }
    }
}
